### ISSUE TITLE
Implement the time bounding query

### ISSUE THREAD

**Issue by jkerr5** [koopjs/koop-provider-marklogic#13]
Handle the `time` query parameter to limit the time instant or the time extent to query.

See: https://developers.arcgis.com/rest/services-reference/query-feature-service-layer-.htm

**Comment by jkerr5** [comment]
We will need something in the feature service descriptor to tell the service what column or range index to use for the time range queries.

If we use a range index, it needs to go in the bounding CTS query and the rows that are returned will only be from documents that match the given time range.

If we use a date/time column from the row, it needs the date range query term needs to be added to the optic where query.

**Comment by jkerr5** [comment]
@jmamanpara, looking at the koop code, it looks like they will pass through `timeInfo` metadata that comes from the provider. 

Try including `timeInfo` in the layer `metadata` in the `generateServiceDescriptor()` function of the provider.

**Comment by gduplantier** [comment]
I have a basic capability working for my project.  I can expand this and submit a pull request.  Currently I only support the row data/optic query.  I can look into adding to the bounding query as well.  I also assume documents are in UTC time.  I'll need to add code that looks at the timeReference section and converts to the properly configured TZ offset.  Will also need to do some date math for date ranges (start/end time, as opposed to just a start time)

**Comment by jkerr5** [comment]
This is covered in GDS already.
