### ISSUE TITLE
Add tests for LineString data

### ISSUE THREAD

**Issue by tdiepenbrock** [koopjs/koop-provider-marklogic#136]
The Koop framework from ESRI appears to understand a geometryType of "LineString" but the koop-provider-marklogic project only has test cases for geometryType="Polygon" and geometryType="Point".  We need to add test data for "LineString" also, since our clients/customers typically need to support those three geometry types at a minimum.

**Comment by jkerr5** [comment]
This is implemented in the geo data services backend
