### ISSUE TITLE
Add the ability to get geometry from a column but don't return the column as a feature field

### ISSUE THREAD

**Issue by jkerr5** [koopjs/koop-provider-marklogic#138]
The current implementation requires the column to be selected from the view in order to be in scope for the Optic plan but there is no way to select it only to extract the geometry an not include it in the feature properties.

**Comment by jkerr5** [comment]
This needs to move to https://github.com/marklogic-community/marklogic-geo-data-services

**Comment by mitchshepherd** [comment]
Moved to GDS
