### ISSUE TITLE
Improve handling of OBJECTIDs

### ISSUE THREAD

**Issue by jkerr5** [koopjs/koop-provider-marklogic#15]
Make it easier to deal with OBJECTIDs that need to be generated.

Get a better understanding of the requirements/constraints for OBJECTID values in the Esri tools.

Are they only required to be unique within a layer?

**Comment by jgravois** [comment]
> Are they only required to be unique within a layer?

that is correct. [GUIDs](https://blogs.esri.com/esri/arcgis/2009/09/28/guids-as-ids/) on the other hand are globally unique.

**Comment by jkerr5** [comment]
There is already a GDS ticket for this.
