### ISSUE TITLE
Split Koop Provider and backend MarkLogic Geo Data Services

### ISSUE THREAD

**Issue by prestonmcgowan** [koopjs/koop-provider-marklogic#151]
The Koop Provider talks to the MarkLogic Geo Data Services, but the MarkLogic Geo Data Services can do more than just talk to Koop.
Therefore, split the two projects into their own repos.
Koop will stay in this repo and the MarkLogic Geo Data Services will move to a new repo.

**Comment by jkerr5** [comment]
Done https://github.com/marklogic-community/marklogic-geo-data-services
