### ISSUE TITLE
Use /tde prefix when loading templates

### ISSUE THREAD

**Issue by aclavio** [koopjs/koop-provider-marklogic#152]
New versions of ml-gradle don't require TDE templates to use the "tdex" extension.  https://github.com/marklogic-community/ml-gradle/wiki/Loading-schemas

> As of version 2.7.0, TDE rulesets no longer need to have a "tdex" or "tdej" suffix. Instead, any document with a URI starting with "/tde" will be put into the "http://marklogic.com/xdmp/tde" collection.

It would be preferable for TDE's to be stored with their native xml or json file extension in the "templates" directory, and insert them into the schema's DB under /tde/{fsConfig}/.

**Comment by jkerr5** [comment]
Move to the https://github.com/marklogic-community/marklogic-geo-data-services project

**Comment by mitchshepherd** [comment]
Moved to GDS
