### ISSUE TITLE
Export the optic plan

### ISSUE THREAD

**Issue by tdiepenbrock** [koopjs/koop-provider-marklogic#156]
In support of exporting data to CSV, rather than running the optic plan, return the output of Plan.export(), which can then be passed into the v1/rows MarkLogic REST API call.

A complication is that it is currently not possible to export deserialized cts.query() objects.

**Comment by jkerr5** [comment]
@tdiepenbrock is this still needed in koop?

**Comment by jkerr5** [comment]
No longer needed in the koop provider.
