### ISSUE TITLE
handle odd query geometry from some Esri tools

### ISSUE THREAD

**Issue by tdiepenbrock** [koopjs/koop-provider-marklogic#157]
Esri tools sometimes make queries that have values exceeding the extents of WGS-84.  Implement functions to handle these queries gracefully.

**Comment by prestonmcgowan** [comment]
Do you have a sample payload showing the values exceeding the WGS-84 extents?

**Comment by jkerr5** [comment]
@tdiepenbrock do we still need to do anything in the koop provider for this?

**Comment by jkerr5** [comment]
Nothing to implement in the koop provider for this.
