### ISSUE TITLE
Directory Structure refactorization

### ISSUE THREAD

**Issue by prestonmcgowan** [koopjs/koop-provider-marklogic#158]
Refactor the Koop Provider MarkLogic's directory structure to look more nodejs and less gradle.

Create top level directories for:
* config
* koop
* scripts
* test

Rework the README to start koop directly with node instead of through gradle.

Reference: https://blog.risingstack.com/node-hero-node-js-project-structure-tutorial/

**Comment by jkerr5** [comment]
Done
