### ISSUE TITLE
Add support for SSL certificates with a passphrase

### ISSUE THREAD

**Issue by jkerr5** [koopjs/koop-provider-marklogic#160]
The koop server.js and config need to be modified to allow a passphrase to be configured for a certificate.

**Comment by rjrudin** [comment]
We now have docs on the develop branch for enabling SSL - https://github.com/koopjs/koop-provider-marklogic/blob/develop/docs/install.md#enabling-ssl . This is intended to be a simple example of how to configure SSL. Customers are free to use our server.js as a starting point to code up any approach they want to managing SSL and certificates.
