### ISSUE TITLE
Consider adding new routes to add/update features

### ISSUE THREAD

**Issue by mfgumban** [koopjs/koop-provider-marklogic#163]
Related to [MarkLogic ArcGIS Pro Addin](https://github.com/marklogic-community/marklogic-arcgis-pro-addin):

- The addin currently connects to both Koop and MarkLogic servers, the former for features while the latter for adding/updating feature layers, acting as a sort of "saved search" mechanism.
- Requiring both servers to be accessible might be an issue for IT for many reasons, such as security policies.
- It would be better if the addin just connects using a single entry point (Koop).  This would mean adding new routes that conform to the GeoServices spec, such as "FeatureServer/:layer/addFeature", which the addin could potentially use.

**Comment by jkerr5** [comment]
This was implemented in release 1.1.2.
