### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by mfgumban** [koopjs/koop-provider-marklogic#164]
Scenario:
- ML server is up but currently "busy" (ingesting large data)
- User hits Koop with a query
- Koop tries to contact ML but will get an error
- Koop will exit because it wasn't able to properly handle the error response

Sample Error:
```
koop          | /app/node_modules/marklogic/node_modules/bluebird/js/release/async.js:61
koop          |         fn = function () { throw arg; };
koop          |                            ^
koop          |
koop          | TypeError: Cannot read property 'errorResponse' of undefined
koop          |     at /app/src/koop/query.js:23:33
```

Code in line 23: `reject(new Error(error.body.errorResponse.message));` needs to be modified to inspect `error.body` first, then make an appropriate action.

**Comment by rjrudin** [comment]
OBE, the line of code this refers to no longer exists.
