### ISSUE TITLE
Refactor query.js

### ISSUE THREAD

**Issue by jkerr5** [koopjs/koop-provider-marklogic#17]
Refactor to make sure the MarkLogic DatabaseClient is being created and used optimally.

**Comment by rjrudin** [comment]
I think this was addressed by Tom D via the `dbClientManager.js` module, where there's some custom code for caching client instances based on username. 

Thus, the goal of this ticket has been accomplished, though we'll need to adopt a different strategy in the future if/when we support MarkLogic authentication techniques that don't depend on a username.
