### ISSUE TITLE
returnGeometry should default to true

### ISSUE THREAD

**Issue by mfgumban** [koopjs/koop-provider-marklogic#171]
As per <https://developers.arcgis.com/rest/services-reference/query-feature-service-layer-.htm>, the default value for the `returnGeometry` parameter is `true`.  Ensure that this parameter is set to `true` when calling `geoQuerySerivce` if the incoming request doesn't explicitly specify it.

**Comment by jkerr5** [comment]
This should be handled in geo data services.
