### ISSUE TITLE
Improve config setup and documentation

### ISSUE THREAD

**Issue by jkerr5** [koopjs/koop-provider-marklogic#176]
The setup of the files in the `config` folders could be improved. 

There should be a `default.json` that has the default values that we want set. There should also be a file called `custom-environment-variables.json` that allows parameters like usernames and passwords to be set via environment variables. 

The documentation should be improved to indicate how to override the configuration using an environment-specific config file as well as what parameters could be set using actual environment variables.

**Comment by rjrudin** [comment]
I think this is OBE - there are multiple config files now, and I think the README adequately describes when to use each one and how to customize "default.json". 

At least, before we release 2.0, we'll ensure that the README provides coverage of what's supported in a config file.
