### ISSUE TITLE
Performance issue in koop featureservice request

### ISSUE THREAD

**Issue by MayuriSivanesan** [koopjs/koop-provider-marklogic#179]
We have begun load testing of about 100 concurrent users for our koop-provider-marklogic project. With every request the time taken to fetch features from featureserver gradually increases. Some of them taking nearly more than 70secs to complete which affects application's performance. We have around 20000 features in featureservice and querying for about 5000 features at once.
There are no errors found in the server log.
The time taken to complete each response is shown as graph in the attached image
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/72431336/141436737-b447f27c-949b-4307-890d-f732fff1335c.png)

**Comment by jkerr5** [comment]
What does the performance look like on the MarkLogic side? Are the requests serviced quickly? I believe the koop logs should should the request times but you can also just look at the meters data on the MarkLogic side.

**Comment by MayuriSivanesan** [comment]
Please refer attached file for server logs from koop and meters data from marklogic
[MarkLogic geoQueryService performance.docx](https://github.com/koopjs/koop-provider-marklogic/files/7552341/MarkLogic.geoQueryService.performance.docx)

**Comment by jkerr5** [comment]
It looks clear that this is a resource limitation on the backend and not an issue with the koop provider so I will close this for now. If it is determined that the provider is a bottleneck of some sort in the future, we can reopen it.
