### ISSUE TITLE
Remove the use of the flora parser

### ISSUE THREAD

**Issue by jkerr5** [koopjs/koop-provider-marklogic#20]
MarkLogic 9.0-4 should add a new optic function to parse a SQL where clause so the flora parser will no longer be needed. Refactor as necessary.

**Comment by jkerr5** [comment]
MarkLogic 9.0-4 has been released and now supports a SQL where expression as a where clause. We can now do something like
```
.where(op.sqlCondition("OBJECTID IN (57011, 34484)"))
```
instead of using the flora sql parser.

We may still need to leverage the flora sql parser to implement #11 as that would require handling some custom SQL function.

This may also fix #7 so check once this is complete.

**Comment by jkerr5** [comment]
Move to GDS and reevaluate if we can get rid of the flora SQL parser given the current handling of SQL where clauses in the optic API.

**Comment by mitchshepherd** [comment]
Moved to GDS
