### ISSUE TITLE
Upgrade the flora sql parser

### ISSUE THREAD

**Issue by jkerr5** [koopjs/koop-provider-marklogic#4]
Move to the most recent version as it supports date/time literals correctly so we can remove the workaround that is in place.

Also look into how to make upgrading this easier in the future as a number of the requires paths have to be updated manually to run inside MarkLogic Server.

If MarkLogic 9.0-4 comes out first, this will be OBE because we will change the SQL where handling to optic (see #20)

**Comment by jkerr5** [comment]
Move to GDS

**Comment by mitchshepherd** [comment]
Moved to GDS
