### ISSUE TITLE
Failed testcase testGkgtoDateWhere

### ISSUE THREAD

**Issue by jmamanpara** [koopjs/koop-provider-marklogic#43]
URL : http://localhost:9080/marklogic/GDeltGKG/FeatureServer/0/query?outFields=urlpubtimedate&returnGeometry=false&where=urlpubtimedate+%3E+TO_DATE%28%271977-12-01+12%3A00%3A00%27%2C%27YYYY-MM-DD+HH24%3AMI%3ASS%27%29&spatialRel=esriSpatialRelIntersects

testGkgtoDateWhere

java.lang.AssertionError: 1 expectation failed.
JSON path features[0].attributes.urlpubtimedate doesn't match.
Expected: is <1495616400000L>
  Actual: 1495605600000

**Comment by mitchshepherd** [comment]
Moved to GDS
