### ISSUE TITLE
Set useStandardizedQueries to true for all layers

### ISSUE THREAD

**Issue by jkerr5** [koopjs/koop-provider-marklogic#50]
The layer metadata should contain `useStandardizedQueries : true` such that clients only send in "standard SQL" (SQL 92)

**Comment by jkerr5** [comment]
Move to GDS. Check if this is done already though.

**Comment by mitchshepherd** [comment]
Moved to GDS

**Comment by mitchshepherd** [comment]
Moved to GDS
