### ISSUE TITLE
ObjectIds parameter is not considered while aggregation

### ISSUE THREAD

**Issue by jmamanpara** [koopjs/koop-provider-marklogic#65]
Connector code is skipping objectIds parameter while aggregation. Hence it returns the count for all documents in a layer.

URL : /marklogic/GDeltGKG/FeatureServer/0/query?objectIds=56577%2C56576&returnCountOnly=true
Actual Result : 38765
Expected Result : 2

**Comment by mitchshepherd** [comment]
Moved to GDS
