### ISSUE TITLE
Index path construction and unfiltered searches

### ISSUE THREAD

**Issue by mfgumban** [koopjs/koop-provider-marklogic#72]
I've encountered an issue with unfiltered searches and how paths are defined for geospatial indexes.

Using the example content we use the following structured query:
```
<query xmlns="http://marklogic.com/appservices/search">
  <term-query>
  	<text>berlin</text>
  </term-query>
  <geospatial-constraint-query>
    <constraint-name>Location</constraint-name>
    <box>
    	<south>-5</south>
    	<west>-28</west>
    	<north>37</north>
    	<east>40</east>
    </box>
  </geospatial-constraint-query>
</query>
```
where "Location" is a geo-path constraint.  The expected results are 4 documents.  If we remove the `geospatial-constraint-query` and retain the `term-query`, the expected results are 222  documents.

Using the original "//" path: `//geometry[type = "Point"]//array-node("coordinates")`:
- filtered: v1/search returns 4, but v1/values returns 222 (sum of frequencies)
- unfiltered: both return 222

If we remove "//": `/geometry[type = "Point"]/array-node("coordinates")`
- filtered: both return 4
- unfiltered: both return 4

If we try using "//" only at the start: `//geometry[type = "Point"]/array-node("coordinates")`, we get the same results as that of the original paths.

Has anyone encountered this in other environments?  Using ML 9.0-3 at the moment.

**Comment by jkerr5** [comment]
There were fixes to unfiltered geo searches in 9.0-4 so please upgrade and test that first.
