### ISSUE TITLE
Improve URLs returned by KoopFeatureLayer

### ISSUE THREAD

**Issue by mfgumban** [koopjs/koop-provider-marklogic#80]
It seems ArcGIS Pro (at least on beta 2.2) has an issue with the following kind of URL:
`https://[domain]:443/path-to-feature-server`
Where the port is explicitly written (443) but is the default/implicit value of the protocol (https).

The KoopFeatureLayer extension should check if Koop is using the default port for the currently set protocol and return a "cleaner" URL by not appending the port.

**Comment by mfgumban** [comment]
Looks like there are other underlying changes with the beta that has affected HTTPS (HTTP seems to work ok).  "Cleaner" URLs is still a good thing to do, though.

**Comment by jkerr5** [comment]
Closing this for now as it would be in GDS but is no longer needed.
