### ISSUE TITLE
Add a gradle task to scaffold new feature services 

### ISSUE THREAD

**Issue by jkerr5** [koopjs/koop-provider-marklogic#95]
Something like `newService`  with the following parameters:
* name - `<string>` The service name
* configName (optional) - `[string]` A top-level configuration name that services can be grouped under. If not specified the service name will be used for the config name.
* searchApi (optional) - `[true|false]` Whether or not the service should have a configuration to support the MarkLogic search API. This is used primarily by the ArcGIS Pro add-in. Defaults to `false`.

Note
> Service name must be a string that is a valid part of a URL path. There should be more checks to make sure this is the case but there are not right now.

**Comment by jkerr5** [comment]
Move to GDS (check for existing ticket already)

**Comment by mitchshepherd** [comment]
Moved to GDS
